### ISSUE TITLE
NPC Happiness guide on the wiki

### ISSUE THREAD

**Issue by bryanclst** [tureptor/terraoptifind#1]
Hi,

Sorry if this in an inappropriate use of issues, but I couldn't figure out how to contact you otherwise. Could you check out the comment I left under "Newer Strategy" on the talk page for NPC Happiness?
https://terraria.wiki.gg/wiki/Guide_talk:NPC_Happiness

**Comment by tureptor** [comment]
No prob, just added my email to my profile, but you're welcome to open issues in the future like this as well.

RE: your comment, it is indeed a remnant of an older version that has the issue you mentioned. I fixed it in my latest commit (16 March), but I forgot to update the wiki page. Feel free to fix it or replace it with a "smarter" layout (e.g. priority for the tinkerer).

**Comment by bryanclst** [comment]
Thanks, I'll update it sometime with a new optimal version from your calculator, as well as some variants.
