### ISSUE TITLE
Ocean+Desert hybrids shown incorrectly

### ISSUE THREAD

**Issue by InSimpleTermsJordan** [tureptor/terraoptifind#9]
Testing with current Terraria version reveals that NPCs cannot recognize deserts within the ocean x-limit, meaning desert+ocean hybrids are impossible ingame as only the ocean biome will be recognized

**Comment by tureptor** [comment]
Desert+ocean is impossible, but Hallowed desert+ocean is possible, and still counts as a desert biome for both happiness and pylons (just tested this on 1.4.4.9). The app only has the hallow/desert/ocean combo as part of possible biomes - [check the top of this file to see what biomes are tested](https://raw.githubusercontent.com/tureptor/terraoptifind/main/npcdata.js)
![arms dealer happiness in hallowed/desert/ocean](https://github.com/tureptor/terraoptifind/assets/98993342/e95dfd3d-b3fc-4742-b9b7-6fc323140e83)
![arms dealer pylons in hallowed/desert/ocean](https://github.com/tureptor/terraoptifind/assets/98993342/f46f20ef-8502-45c7-a304-6960aa398bf9)

**Comment by InSimpleTermsJordan** [comment]
Interesting. I had only tested with 125 pearlstone blocks and 1500 sand blocks nearby, rather than the 1500 pearlsand that would be present in a natural hallow desert, which does seem to work
